### ISSUE TITLE
Telegram Special Bot - Automation and Component Alert event

### ISSUE THREAD

**Issue by dakweenduck** [der-optimist/hass#1]
Trying to use the "special_bot" target to trigger event  from HA  automations, but facing an error:

Automations Config in automations.yaml:

- id: 'xxxxxxxxxxx'
  alias: Test Bot 2
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sne_lx2_charger_type
    from: none
    to: ac
  condition: []
  action:
  - event: custom_notify
    event_data:
      customData:
      - message: Test
      - target: special_bot
      - special_bot_api_key: 1111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - special_bot_chat_id: '1111111111'
  mode: single

Below is the error output.

The app receives the "custom_notify" event but it appears to be issue with args  passed:

2020-11-29 09:00:22.644857 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/custom_notify.py
2020-11-29 09:00:22.648762 INFO AppDaemon: Initializing app custom_notify using class custom_notify from module custom_notify
2020-11-29 09:00:22.784965 INFO AppDaemon: App initialization complete
2020-11-29 09:00:31.976747 WARNING custom_notify: ------------------------------------------------------------
2020-11-29 09:00:31.977942 WARNING custom_notify: Unexpected error in worker for App custom_notify:
2020-11-29 09:00:31.978749 WARNING custom_notify: Worker Ags: {'id': 'xxxxxxxx', 'name': 'custom_notify', 'objectid': 'xxxxx, 'type': 'event', 'event': 'custom_notify', 'function': <bound method custom_notify.notification_received of <custom_notify.custom_notify object at 0x7f3a6c32eaf0>>, 'data': {'customData': [{'message': 'Test'}, {'target': 'special_bot'}, {'special_bot_api_key': '1111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}, {'special_bot_chat_id': '1111111111'}]}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2020-11-29 09:00:31.979506 WARNING custom_notify: ------------------------------------------------------------
2020-11-29 09:00:31.986511 WARNING custom_notify: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 933, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/custom_notify.py", line 27, in notification_received
    data["message"] = data["message"].replace("_"," ").replace("*"," ")
KeyError: 'message'
2020-11-29 09:00:31.986884 WARNING custom_notify: ------------------------------------------------------------
 
Any ideas and could you perhaps point me in right direction?

Also is it possible to use "Special_bot" target in a HA component "alert"?

What should the "notify" config look like for "special_bot" (not sure how it calls the event "custom_notify") and a bit confused as to how to add the  special_bot_api_key and  special_bot_chat_id for notify? 

notify:
  - platform: telegram
    name: Telegram
    chat_id: xxxxxxxxx
  - platform: telegram
    name: special_bot
    chat_id: xxxxxxxxx

Config in configuration.yaml:

alert:
  garage_door_open_long:
    name: Main Gate LEFT OPEN!!!
    entity_id: sensor.MainGate_Open
    state: 'True'   
    repeat: 1
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - telegram.special_bot

Tried going through your configuration.yaml and all apps for hints but no luck, would appreciate your help.

Default telegram bot works fine.

**Comment by Rotif** [comment]
I have the same problem, pleas could somebody give me hint?
Thank you
